import type { Company } from "../../types.ts";

const PACKAGING_QUERY = "packaging";
/** Prefer engineer/package-dev keywords first; keep packaging as a fallback net. */
const ENGINEER_QUERIES = [
  "packaging engineer",
  "package development",
  "packaging",
] as const;
const ENGINEER_ONLY = [
  "packaging engineer",
  "package development",
] as const;

export const companies: Company[] = [
  {
    name: "Kimberly-Clark",
    slug: "kimberly-clark",
    ats: "workday",
    careerUrl: "https://kimberlyclark.wd1.myworkdayjobs.com/GLOBAL",
    host: "kimberlyclark.wd1.myworkdayjobs.com",
    tenant: "kimberlyclark",
    site: "GLOBAL",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    niche: "cpg",
  },
  {
    name: "General Mills",
    slug: "general-mills",
    ats: "workday",
    careerUrl: "https://genmills.wd1.myworkdayjobs.com/GMI_External_Careers",
    host: "genmills.wd1.myworkdayjobs.com",
    tenant: "genmills",
    site: "GMI_External_Careers",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    niche: "food-beverage",
  },
  {
    name: "Sonoco",
    slug: "sonoco",
    ats: "workday",
    careerUrl: "https://sonoco.wd1.myworkdayjobs.com/CorporateCareers",
    host: "sonoco.wd1.myworkdayjobs.com",
    tenant: "sonoco",
    site: "CorporateCareers",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    niche: "industrial",
  },
  {
    name: "3M",
    slug: "3m",
    ats: "workday",
    careerUrl: "https://3m.wd1.myworkdayjobs.com/Search",
    host: "3m.wd1.myworkdayjobs.com",
    tenant: "3m",
    site: "Search",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "industrial",
  },
  {
    name: "Kenvue",
    slug: "kenvue",
    ats: "workday",
    careerUrl: "https://kenvue.wd5.myworkdayjobs.com/kenvue",
    host: "kenvue.wd5.myworkdayjobs.com",
    tenant: "kenvue",
    site: "kenvue",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    niche: "cpg",
    country: "USA",
  },
  {
    name: "Clorox",
    slug: "clorox",
    ats: "workday",
    careerUrl: "https://clorox.wd1.myworkdayjobs.com/Clorox",
    host: "clorox.wd1.myworkdayjobs.com",
    tenant: "clorox",
    site: "Clorox",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "cpg",
  },
  {
    name: "Conagra Brands",
    slug: "conagra",
    ats: "workday",
    careerUrl: "https://conagrabrands.wd1.myworkdayjobs.com/Careers_US",
    host: "conagrabrands.wd1.myworkdayjobs.com",
    tenant: "conagrabrands",
    site: "Careers_US",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "food-beverage",
  },
  {
    name: "Campbell's",
    slug: "campbells",
    ats: "workday",
    careerUrl:
      "https://campbellsoup.wd5.myworkdayjobs.com/ExternalCareers_GlobalSite",
    host: "campbellsoup.wd5.myworkdayjobs.com",
    tenant: "campbellsoup",
    site: "ExternalCareers_GlobalSite",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "food-beverage",
  },
  {
    name: "Church & Dwight",
    slug: "church-dwight",
    ats: "workday",
    careerUrl: "https://churchdwight.wd1.myworkdayjobs.com/chdcareers",
    host: "churchdwight.wd1.myworkdayjobs.com",
    tenant: "churchdwight",
    site: "chdcareers",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "cpg",
  },
  {
    name: "SC Johnson",
    slug: "sc-johnson",
    ats: "workday",
    careerUrl: "https://scj.wd5.myworkdayjobs.com/External_Career_Site",
    host: "scj.wd5.myworkdayjobs.com",
    tenant: "scj",
    site: "External_Career_Site",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "cpg",
  },
  {
    name: "J.M. Smucker",
    slug: "smucker",
    ats: "workday",
    careerUrl: "https://smucker.wd5.myworkdayjobs.com/US_External_Careers",
    host: "smucker.wd5.myworkdayjobs.com",
    tenant: "smucker",
    site: "US_External_Careers",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "food-beverage",
  },
  {
    name: "Silgan Containers",
    slug: "silgan-containers",
    ats: "workday",
    careerUrl: "https://silgancontainers.wd1.myworkdayjobs.com/silgan",
    host: "silgancontainers.wd1.myworkdayjobs.com",
    tenant: "silgancontainers",
    site: "silgan",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    niche: "industrial",
  },
  {
    name: "Silgan Dispensing",
    slug: "silgan-dispensing",
    ats: "workday",
    careerUrl: "https://silgandispensing.wd501.myworkdayjobs.com/silgan",
    host: "silgandispensing.wd501.myworkdayjobs.com",
    tenant: "silgandispensing",
    site: "silgan",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    niche: "industrial",
  },
  {
    name: "Aptar",
    slug: "aptar",
    ats: "successfactors",
    careerUrl: "https://jobs.aptar.com",
    searchText: PACKAGING_QUERY,
    niche: "industrial",
  },
  {
    name: "Autoliv",
    slug: "autoliv",
    ats: "teamtailor",
    careerUrl: "https://careerunitedstates.autoliv.com/jobs",
    searchText: PACKAGING_QUERY,
    niche: "automotive",
  },
  {
    name: "General Motors",
    slug: "general-motors",
    ats: "workday",
    careerUrl: "https://generalmotors.wd5.myworkdayjobs.com/Careers_GM",
    host: "generalmotors.wd5.myworkdayjobs.com",
    tenant: "generalmotors",
    site: "Careers_GM",
    searchText: PACKAGING_QUERY,
    country: "USA",
    niche: "automotive",
  },
  {
    name: "Magna",
    slug: "magna",
    ats: "workday",
    careerUrl: "https://magna.wd3.myworkdayjobs.com/Magna",
    host: "magna.wd3.myworkdayjobs.com",
    tenant: "magna",
    site: "Magna",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "automotive",
  },
  {
    name: "Menasha",
    slug: "menasha",
    ats: "workday",
    careerUrl: "https://menasha.wd12.myworkdayjobs.com/MenashaCorp",
    host: "menasha.wd12.myworkdayjobs.com",
    tenant: "menasha",
    site: "MenashaCorp",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "industrial",
  },
  {
    name: "International Paper",
    slug: "international-paper",
    ats: "oracle",
    careerUrl:
      "https://iazbqy.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1",
    site: "CX_1",
    searchText: PACKAGING_QUERY,
    niche: "industrial",
  },
  {
    name: "PepsiCo",
    slug: "pepsico",
    ats: "jibe",
    careerUrl: "https://www.pepsicojobs.com/main",
    searchText: PACKAGING_QUERY,
    country: "USA",
    niche: "food-beverage",
  },
  {
    name: "Unilever",
    slug: "unilever",
    ats: "workday",
    careerUrl:
      "https://unilever.wd3.myworkdayjobs.com/Unilever_Experienced_Professionals",
    host: "unilever.wd3.myworkdayjobs.com",
    tenant: "unilever",
    site: "Unilever_Experienced_Professionals",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "cpg",
  },
  {
    name: "Johnson & Johnson",
    slug: "johnson-johnson",
    ats: "workday",
    careerUrl: "https://jj.wd5.myworkdayjobs.com/JJ",
    host: "jj.wd5.myworkdayjobs.com",
    tenant: "jj",
    site: "JJ",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "pharma",
  },
  {
    name: "Procter & Gamble",
    slug: "pg",
    ats: "phenom",
    careerUrl: "https://www.pgcareers.com/us/en",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    refNum: "PGBPGNGLOBAL",
    niche: "cpg",
  },
  {
    name: "The Coca-Cola Company",
    slug: "coca-cola-company",
    ats: "cws",
    careerUrl: "https://careers.coca-colacompany.com",
    host: "jobsapi-internal.m-cloud.io",
    orgId: "2110",
    searchText: PACKAGING_QUERY,
    facets: [
      "ats_portalid:CocaCola-Workday-External",
      "is_internal:coca-cola-careers",
      "primary_country:US",
    ],
    niche: "food-beverage",
  },
  {
    name: "DuPont",
    slug: "dupont",
    ats: "phenom",
    careerUrl: "https://careers.dupont.com/us/en",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    refNum: "DUPOUS",
    niche: "industrial",
  },
  {
    name: "WK Kellogg Co",
    slug: "wk-kellogg",
    ats: "phenom",
    careerUrl: "https://jobs.wkkellogg.com/us/en/search-results",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    refNum: "WKNWKIUS",
    country: "USA",
    niche: "food-beverage",
  },
  {
    name: "Mars",
    slug: "mars",
    ats: "phenom",
    careerUrl: "https://careers.mars.com/us/en",
    searchText: PACKAGING_QUERY,
    searchTexts: [...ENGINEER_QUERIES],
    refNum: "MARSGLOBAL",
    country: "USA",
    niche: "food-beverage",
  },
  {
    name: "Ball Corporation",
    slug: "ball",
    ats: "successfactors",
    careerUrl: "https://jobs.ball.com",
    searchText: PACKAGING_QUERY,
    niche: "cpg",
  },
  {
    name: "Sealed Air",
    slug: "sealed-air",
    ats: "successfactors",
    careerUrl: "https://jobs.sealedair.com",
    searchText: PACKAGING_QUERY,
    niche: "industrial",
  },
  {
    name: "Amcor",
    slug: "amcor",
    ats: "successfactors",
    careerUrl: "https://jobs-sf.amcor.com",
    searchText: PACKAGING_QUERY,
    niche: "industrial",
  },
  {
    name: "Nestlé",
    slug: "nestle",
    ats: "successfactors",
    careerUrl: "https://www.nestlejobs.com",
    searchText: PACKAGING_QUERY,
    niche: "food-beverage",
  },
  {
    name: "Berlin Packaging",
    slug: "berlin-packaging",
    ats: "greenhouse",
    careerUrl: "https://job-boards.greenhouse.io/berlinpackaging",
    boardToken: "berlinpackaging",
    niche: "industrial",
  },
  {
    name: "Ernest Packaging",
    slug: "ernest-packaging",
    ats: "greenhouse",
    careerUrl: "https://job-boards.greenhouse.io/ernestpackagingsolutions",
    boardToken: "ernestpackagingsolutions",
    niche: "industrial",
  },
  {
    name: "Amazon",
    slug: "amazon",
    ats: "amazon",
    careerUrl: "https://www.amazon.jobs",
    searchText: "packaging engineer",
    country: "USA",
    niche: "industrial",
  },
  // --- Moonshot additions (CPG / pharma / medtech / converters) ---
  {
    name: "Abbott",
    slug: "abbott",
    ats: "workday",
    careerUrl: "https://abbott.wd5.myworkdayjobs.com/abbottcareers",
    host: "abbott.wd5.myworkdayjobs.com",
    tenant: "abbott",
    site: "abbottcareers",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "pharma",
  },
  {
    name: "Pfizer",
    slug: "pfizer",
    ats: "workday",
    careerUrl: "https://pfizer.wd1.myworkdayjobs.com/PfizerCareers",
    host: "pfizer.wd1.myworkdayjobs.com",
    tenant: "pfizer",
    site: "PfizerCareers",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_ONLY],
    country: "USA",
    niche: "pharma",
  },
  {
    name: "Baxter",
    slug: "baxter",
    ats: "workday",
    careerUrl: "https://baxter.wd1.myworkdayjobs.com/Baxter",
    host: "baxter.wd1.myworkdayjobs.com",
    tenant: "baxter",
    site: "Baxter",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "pharma",
  },
  {
    name: "Stryker",
    slug: "stryker",
    ats: "workday",
    careerUrl: "https://stryker.wd1.myworkdayjobs.com/StrykerCareers",
    host: "stryker.wd1.myworkdayjobs.com",
    tenant: "stryker",
    site: "StrykerCareers",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "pharma",
  },
  {
    name: "Catalent",
    slug: "catalent",
    ats: "workday",
    careerUrl: "https://catalent.wd1.myworkdayjobs.com/External",
    host: "catalent.wd1.myworkdayjobs.com",
    tenant: "catalent",
    site: "External",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_ONLY],
    country: "USA",
    niche: "pharma",
  },
  {
    name: "Tyson Foods",
    slug: "tyson",
    ats: "workday",
    careerUrl: "https://tysonfoods.wd5.myworkdayjobs.com/TSN",
    host: "tysonfoods.wd5.myworkdayjobs.com",
    tenant: "tysonfoods",
    site: "TSN",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_ONLY],
    country: "USA",
    niche: "food-beverage",
  },
  {
    name: "Constellation Brands",
    slug: "constellation",
    ats: "workday",
    careerUrl: "https://cbrands.wd5.myworkdayjobs.com/CBI_External_Careers",
    host: "cbrands.wd5.myworkdayjobs.com",
    tenant: "cbrands",
    site: "CBI_External_Careers",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_ONLY],
    country: "USA",
    niche: "food-beverage",
  },
  {
    name: "Target",
    slug: "target",
    ats: "workday",
    careerUrl: "https://target.wd5.myworkdayjobs.com/targetcareers",
    host: "target.wd5.myworkdayjobs.com",
    tenant: "target",
    site: "targetcareers",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "cpg",
  },
  {
    name: "CHEP",
    slug: "chep",
    ats: "workday",
    careerUrl: "https://brambles.wd5.myworkdayjobs.com/Brambles_Careers",
    host: "brambles.wd5.myworkdayjobs.com",
    tenant: "brambles",
    site: "Brambles_Careers",
    searchText: "packaging engineer",
    searchTexts: ["packaging engineer", "returnable packaging", "dunnage", "packaging"],
    country: "USA",
    niche: "automotive",
  },
  {
    name: "Thermo Fisher Scientific",
    slug: "thermo-fisher",
    ats: "workday",
    careerUrl: "https://thermofisher.wd5.myworkdayjobs.com/ThermoFisherCareers",
    host: "thermofisher.wd5.myworkdayjobs.com",
    tenant: "thermofisher",
    site: "ThermoFisherCareers",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "pharma",
  },
  {
    name: "BD",
    slug: "bd",
    ats: "workday",
    careerUrl: "https://bdx.wd1.myworkdayjobs.com/EXTERNAL_CAREER_SITE_USA",
    host: "bdx.wd1.myworkdayjobs.com",
    tenant: "bdx",
    site: "EXTERNAL_CAREER_SITE_USA",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "pharma",
  },
  {
    name: "The Hershey Company",
    slug: "hershey",
    ats: "successfactors",
    careerUrl: "https://careers.thehersheycompany.com",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_QUERIES],
    niche: "food-beverage",
  },
  {
    name: "Eastman",
    slug: "eastman",
    ats: "successfactors",
    careerUrl: "https://jobs.eastman.com",
    searchText: "packaging",
    searchTexts: ["packaging engineer", "flexible packaging", "packaging"],
    niche: "industrial",
  },
  {
    name: "Molson Coors",
    slug: "molson-coors",
    ats: "successfactors",
    careerUrl: "https://jobs.molsoncoors.com",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_ONLY],
    niche: "food-beverage",
  },
  {
    name: "Reckitt",
    slug: "reckitt",
    ats: "successfactors",
    careerUrl: "https://careers.reckitt.com",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_ONLY],
    niche: "cpg",
  },
  {
    name: "E&J Gallo",
    slug: "gallo",
    ats: "successfactors",
    careerUrl: "https://careers.gallo.com",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_QUERIES],
    niche: "food-beverage",
  },
  {
    name: "Colgate-Palmolive",
    slug: "colgate",
    ats: "successfactors",
    careerUrl: "https://jobs.colgate.com",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_QUERIES],
    niche: "cpg",
  },
  {
    name: "Perrigo",
    slug: "perrigo",
    ats: "successfactors",
    careerUrl: "https://careers.perrigo.com",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_ONLY],
    niche: "pharma",
  },
  {
    name: "Edwards Lifesciences",
    slug: "edwards",
    ats: "workday",
    careerUrl: "https://edwards.wd5.myworkdayjobs.com/EdwardsCareers",
    host: "edwards.wd5.myworkdayjobs.com",
    tenant: "edwards",
    site: "EdwardsCareers",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_QUERIES],
    country: "USA",
    niche: "pharma",
  },
  {
    name: "Medtronic",
    slug: "medtronic",
    ats: "workday",
    careerUrl: "https://medtronic.wd1.myworkdayjobs.com/MedtronicCareers",
    host: "medtronic.wd1.myworkdayjobs.com",
    tenant: "medtronic",
    site: "MedtronicCareers",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_ONLY],
    country: "USA",
    niche: "pharma",
  },
  {
    name: "Zimmer Biomet",
    slug: "zimmer-biomet",
    ats: "phenom",
    careerUrl: "https://careers.zimmerbiomet.com/us/en",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_ONLY],
    refNum: "ZBUZBRUS",
    country: "USA",
    niche: "pharma",
  },
  {
    name: "Sargento",
    slug: "sargento",
    ats: "phenom",
    careerUrl: "https://careers.sargento.com/us/en",
    searchText: "packaging engineer",
    searchTexts: [...ENGINEER_QUERIES],
    refNum: "SFINUS",
    country: "USA",
    niche: "food-beverage",
  },
  {
    name: "GSK",
    slug: "gsk",
    ats: "workday",
    careerUrl: "https://gsk.wd5.myworkdayjobs.com/GSKCareers",
    host: "gsk.wd5.myworkdayjobs.com",
    tenant: "gsk",
    site: "GSKCareers",
    searchText: "packaging engineer",
    searchTexts: ["packaging engineer", "device and packaging", "packaging technologist"],
    country: "USA",
    niche: "pharma",
  },

];
