import type { Company } from "../../types.ts";

const DR_QUERIES = [
  "business continuity",
  "disaster recovery",
  "operational resilience",
  "continuity of business",
  "BCM",
  "crisis management",
  "business resilience",
  "technology resilience",
  "DR architect",
  "continuity planning",
  "BCP",
  "resiliency",
  "emergency management",
] as const;

export const companies: Company[] = [
  // Wave 0 — repaired / verified existing
  {
    name: "Bank of America",
    slug: "bank-of-america",
    ats: "workday",
    careerUrl: "https://ghr.wd1.myworkdayjobs.com/en-US/Lateral-US",
    host: "ghr.wd1.myworkdayjobs.com",
    tenant: "ghr",
    site: "Lateral-US",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "Wells Fargo",
    slug: "wells-fargo",
    ats: "workday",
    careerUrl: "https://wf.wd1.myworkdayjobs.com/en-US/WellsFargoJobs",
    host: "wf.wd1.myworkdayjobs.com",
    tenant: "wf",
    site: "WellsFargoJobs",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "Citigroup",
    slug: "citigroup",
    ats: "workday",
    careerUrl: "https://citi.wd5.myworkdayjobs.com/2",
    host: "citi.wd5.myworkdayjobs.com",
    tenant: "citi",
    site: "2",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "Elevance Health",
    slug: "elevance-health",
    ats: "workday",
    careerUrl: "https://elevancehealth.wd1.myworkdayjobs.com/ANT",
    host: "elevancehealth.wd1.myworkdayjobs.com",
    tenant: "elevancehealth",
    site: "ANT",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "insurance",
  },
  {
    name: "Cigna",
    slug: "cigna",
    ats: "workday",
    careerUrl: "https://cigna.wd5.myworkdayjobs.com/en-US/cignacareers",
    host: "cigna.wd5.myworkdayjobs.com",
    tenant: "cigna",
    site: "cignacareers",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "insurance",
  },
  {
    name: "Humana",
    slug: "humana",
    ats: "workday",
    careerUrl:
      "https://humana.wd5.myworkdayjobs.com/Humana_External_Career_Site",
    host: "humana.wd5.myworkdayjobs.com",
    tenant: "humana",
    site: "Humana_External_Career_Site",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "healthcare",
  },
  // Wave 1 — regulated finance
  {
    name: "Morgan Stanley",
    slug: "morgan-stanley",
    ats: "workday",
    careerUrl: "https://ms.wd5.myworkdayjobs.com/en-US/External",
    host: "ms.wd5.myworkdayjobs.com",
    tenant: "ms",
    site: "External",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "Capital One",
    slug: "capital-one",
    ats: "workday",
    careerUrl: "https://capitalone.wd12.myworkdayjobs.com/Capital_One",
    host: "capitalone.wd12.myworkdayjobs.com",
    tenant: "capitalone",
    site: "Capital_One",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "State Street",
    slug: "state-street",
    ats: "workday",
    careerUrl: "https://statestreet.wd1.myworkdayjobs.com/Global",
    host: "statestreet.wd1.myworkdayjobs.com",
    tenant: "statestreet",
    site: "Global",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "U.S. Bank",
    slug: "us-bank",
    ats: "workday",
    careerUrl: "https://usbank.wd1.myworkdayjobs.com/US_Bank_Careers",
    host: "usbank.wd1.myworkdayjobs.com",
    tenant: "usbank",
    site: "US_Bank_Careers",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "TD Bank",
    slug: "td-bank",
    ats: "workday",
    careerUrl: "https://td.wd3.myworkdayjobs.com/en-US/TD_Bank_Careers",
    host: "td.wd3.myworkdayjobs.com",
    tenant: "td",
    site: "TD_Bank_Careers",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "BMO",
    slug: "bmo",
    ats: "workday",
    careerUrl: "https://bmo.wd3.myworkdayjobs.com/External",
    host: "bmo.wd3.myworkdayjobs.com",
    tenant: "bmo",
    site: "External",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "PayPal",
    slug: "paypal",
    ats: "workday",
    careerUrl: "https://paypal.wd1.myworkdayjobs.com/jobs",
    host: "paypal.wd1.myworkdayjobs.com",
    tenant: "paypal",
    site: "jobs",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  // Wave 2 — insurers / payers
  {
    name: "Travelers",
    slug: "travelers",
    ats: "workday",
    careerUrl: "https://travelers.wd5.myworkdayjobs.com/External",
    host: "travelers.wd5.myworkdayjobs.com",
    tenant: "travelers",
    site: "External",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "insurance",
  },
  {
    name: "AIG",
    slug: "aig",
    ats: "workday",
    careerUrl: "https://aig.wd1.myworkdayjobs.com/en-US/AIG",
    host: "aig.wd1.myworkdayjobs.com",
    tenant: "aig",
    site: "AIG",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "insurance",
  },
  // Wave 3 — enterprise BCM volume (verified title hits)
  {
    name: "Target",
    slug: "target",
    ats: "workday",
    careerUrl: "https://target.wd5.myworkdayjobs.com/targetcareers",
    host: "target.wd5.myworkdayjobs.com",
    tenant: "target",
    site: "targetcareers",
    searchTexts: [...DR_QUERIES],
    country: "USA",
  },
  {
    name: "Duke Energy",
    slug: "duke-energy",
    ats: "workday",
    careerUrl: "https://dukeenergy.wd1.myworkdayjobs.com/en-US/search",
    host: "dukeenergy.wd1.myworkdayjobs.com",
    tenant: "dukeenergy",
    site: "search",
    searchTexts: [...DR_QUERIES],
    country: "USA",
  },
  {
    name: "Neuberger Berman",
    slug: "neuberger-berman",
    ats: "workday",
    careerUrl: "https://nb.wd1.myworkdayjobs.com/en-US/NBCareers",
    host: "nb.wd1.myworkdayjobs.com",
    tenant: "nb",
    site: "NBCareers",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "Twilio",
    slug: "twilio",
    ats: "greenhouse",
    careerUrl: "https://job-boards.greenhouse.io/twilio",
    boardToken: "twilio",
    searchTexts: [...DR_QUERIES],
    country: "USA",
  },
  {
    name: "Waymo",
    slug: "waymo",
    ats: "greenhouse",
    careerUrl: "https://job-boards.greenhouse.io/waymo",
    boardToken: "waymo",
    searchTexts: [...DR_QUERIES],
    country: "USA",
  },
  {
    name: "Cockroach Labs",
    slug: "cockroach-labs",
    ats: "greenhouse",
    careerUrl: "https://job-boards.greenhouse.io/cockroachlabs",
    boardToken: "cockroachlabs",
    searchTexts: [...DR_QUERIES],
    country: "USA",
  },
  // Wave 1–3 verified hits (Workday / Greenhouse / SmartRecruiters)
  {
    name: "The Hartford",
    slug: "the-hartford",
    ats: "workday",
    careerUrl: "https://thehartford.wd5.myworkdayjobs.com/Careers_External",
    host: "thehartford.wd5.myworkdayjobs.com",
    tenant: "thehartford",
    site: "Careers_External",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "insurance",
  },
  {
    name: "Freddie Mac",
    slug: "freddie-mac",
    ats: "workday",
    careerUrl: "https://freddiemac.wd5.myworkdayjobs.com/External",
    host: "freddiemac.wd5.myworkdayjobs.com",
    tenant: "freddiemac",
    site: "External",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "Horizon Blue Cross Blue Shield of New Jersey",
    slug: "horizon-bcbsnj",
    ats: "workday",
    careerUrl: "https://bcbsnj.wd5.myworkdayjobs.com/hc",
    host: "bcbsnj.wd5.myworkdayjobs.com",
    tenant: "bcbsnj",
    site: "hc",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "insurance",
  },
  {
    name: "Intermountain Health",
    slug: "intermountain-health",
    ats: "workday",
    careerUrl: "https://imh.wd108.myworkdayjobs.com/intermountaincareers",
    host: "imh.wd108.myworkdayjobs.com",
    tenant: "imh",
    site: "intermountaincareers",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "healthcare",
  },
  {
    name: "Roche",
    slug: "roche",
    ats: "workday",
    careerUrl: "https://roche.wd3.myworkdayjobs.com/rog-a2o-gene",
    host: "roche.wd3.myworkdayjobs.com",
    tenant: "roche",
    site: "rog-a2o-gene",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "healthcare",
  },
  {
    name: "Airbus",
    slug: "airbus",
    ats: "workday",
    careerUrl: "https://ag.wd3.myworkdayjobs.com/airbus",
    host: "ag.wd3.myworkdayjobs.com",
    tenant: "ag",
    site: "airbus",
    searchTexts: [...DR_QUERIES],
  },
  {
    name: "AbbVie",
    slug: "abbvie",
    ats: "smartrecruiters",
    careerUrl: "https://jobs.smartrecruiters.com/AbbVie",
    boardToken: "AbbVie",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "healthcare",
  },
  {
    name: "Jamf",
    slug: "jamf",
    ats: "greenhouse",
    careerUrl: "https://job-boards.greenhouse.io/jamf",
    boardToken: "jamf",
    searchTexts: [...DR_QUERIES],
    country: "USA",
  },
  {
    name: "SpaceX",
    slug: "spacex",
    ats: "greenhouse",
    careerUrl: "https://job-boards.greenhouse.io/spacex",
    boardToken: "spacex",
    searchTexts: [...DR_QUERIES],
    country: "USA",
  },
  {
    name: "Solventum",
    slug: "solventum",
    ats: "workday",
    careerUrl: "https://healthcare.wd1.myworkdayjobs.com/search",
    host: "healthcare.wd1.myworkdayjobs.com",
    tenant: "healthcare",
    site: "search",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "healthcare",
  },
  {
    name: "Gilead Sciences",
    slug: "gilead",
    ats: "workday",
    careerUrl: "https://gilead.wd1.myworkdayjobs.com/gileadcareers",
    host: "gilead.wd1.myworkdayjobs.com",
    tenant: "gilead",
    site: "gileadcareers",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "healthcare",
  },
  {
    name: "Dick's Sporting Goods",
    slug: "dicks-sporting-goods",
    ats: "workday",
    careerUrl: "https://dickssportinggoods.wd1.myworkdayjobs.com/DSG",
    host: "dickssportinggoods.wd1.myworkdayjobs.com",
    tenant: "dickssportinggoods",
    site: "DSG",
    searchTexts: [...DR_QUERIES],
    country: "USA",
  },
  {
    name: "RTX",
    slug: "rtx",
    ats: "workday",
    careerUrl: "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway",
    host: "globalhr.wd5.myworkdayjobs.com",
    tenant: "globalhr",
    site: "REC_RTX_Ext_Gateway",
    searchTexts: [...DR_QUERIES],
    country: "USA",
  },
  {
    name: "BlueCross BlueShield of Tennessee",
    slug: "bcbst",
    ats: "workday",
    careerUrl: "https://bcbst.wd1.myworkdayjobs.com/external",
    host: "bcbst.wd1.myworkdayjobs.com",
    tenant: "bcbst",
    site: "external",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "insurance",
  },
  {
    name: "Pax8",
    slug: "pax8",
    ats: "workday",
    careerUrl: "https://pax8inc.wd12.myworkdayjobs.com/pax8careers",
    host: "pax8inc.wd12.myworkdayjobs.com",
    tenant: "pax8inc",
    site: "pax8careers",
    searchTexts: [...DR_QUERIES],
    country: "USA",
  },
  // Wave 3 — credit unions + peer regulated employers (MSUFCU read-across)
  {
    name: "MSU Federal Credit Union",
    slug: "msufcu",
    ats: "ultipro",
    careerUrl:
      "https://recruiting.ultipro.com/mic1007/JobBoard/24c0bd68-a7ff-5460-0b4e-fe75a81b0396",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "Visions Federal Credit Union",
    slug: "visions-fcu",
    ats: "ultipro",
    careerUrl:
      "https://recruiting.ultipro.com/VIS1010VFCU/JobBoard/8aa6443c-bdeb-4ca6-a33d-6c538463a2c4",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "SchoolsFirst Federal Credit Union",
    slug: "schoolsfirst-fcu",
    ats: "workday",
    careerUrl: "https://schoolsfirstfcu.wd115.myworkdayjobs.com/Careers",
    host: "schoolsfirstfcu.wd115.myworkdayjobs.com",
    tenant: "schoolsfirstfcu",
    site: "Careers",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "BECU",
    slug: "becu",
    ats: "workday",
    careerUrl: "https://becu.wd1.myworkdayjobs.com/External",
    host: "becu.wd1.myworkdayjobs.com",
    tenant: "becu",
    site: "External",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "Navy Federal Credit Union",
    slug: "navy-federal",
    ats: "oracle",
    careerUrl:
      "https://jobs.navyfederal.org/hcmUI/CandidateExperience/en/sites/nfcu",
    site: "nfcu",
    searchTexts: [...DR_QUERIES],
    country: "USA",
    niche: "finance",
  },
  {
    name: "American Electric Power",
    slug: "aep",
    ats: "workday",
    careerUrl: "https://aep.wd1.myworkdayjobs.com/AEPCareerSite",
    host: "aep.wd1.myworkdayjobs.com",
    tenant: "aep",
    site: "AEPCareerSite",
    searchTexts: [...DR_QUERIES],
    country: "USA",
  },
];
