import type { Company } from "../../types.ts";

const DR_QUERIES = [
  "business continuity",
  "disaster recovery",
  "operational resilience",
  "continuity of business",
  "BCM",
  "crisis management",
] as const;

export const companies: Company[] = [
  // Wave 0 — repaired / verified existing
  {
    name: "Bank of America",
    slug: "bank-of-america",
    ats: "workday",
    careerUrl: "https://ghr.wd1.myworkdayjobs.com/en-US/Lateral-US",
    host: "ghr.wd1.myworkdayjobs.com",
    tenant: "ghr",
    site: "Lateral-US",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "Wells Fargo",
    slug: "wells-fargo",
    ats: "workday",
    careerUrl: "https://wf.wd1.myworkdayjobs.com/en-US/WellsFargoJobs",
    host: "wf.wd1.myworkdayjobs.com",
    tenant: "wf",
    site: "WellsFargoJobs",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "Citigroup",
    slug: "citigroup",
    ats: "workday",
    careerUrl: "https://citi.wd5.myworkdayjobs.com/2",
    host: "citi.wd5.myworkdayjobs.com",
    tenant: "citi",
    site: "2",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "Elevance Health",
    slug: "elevance-health",
    ats: "workday",
    careerUrl: "https://elevancehealth.wd1.myworkdayjobs.com/ANT",
    host: "elevancehealth.wd1.myworkdayjobs.com",
    tenant: "elevancehealth",
    site: "ANT",
    searchTexts: [...DR_QUERIES],
    niche: "insurance",
  },
  {
    name: "Cigna",
    slug: "cigna",
    ats: "workday",
    careerUrl: "https://cigna.wd5.myworkdayjobs.com/en-US/cignacareers",
    host: "cigna.wd5.myworkdayjobs.com",
    tenant: "cigna",
    site: "cignacareers",
    searchTexts: [...DR_QUERIES],
    niche: "insurance",
  },
  {
    name: "Humana",
    slug: "humana",
    ats: "workday",
    careerUrl:
      "https://humana.wd5.myworkdayjobs.com/Humana_External_Career_Site",
    host: "humana.wd5.myworkdayjobs.com",
    tenant: "humana",
    site: "Humana_External_Career_Site",
    searchTexts: [...DR_QUERIES],
    niche: "healthcare",
  },
  // Wave 1 — regulated finance
  {
    name: "Morgan Stanley",
    slug: "morgan-stanley",
    ats: "workday",
    careerUrl: "https://ms.wd5.myworkdayjobs.com/en-US/External",
    host: "ms.wd5.myworkdayjobs.com",
    tenant: "ms",
    site: "External",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "Capital One",
    slug: "capital-one",
    ats: "workday",
    careerUrl: "https://capitalone.wd12.myworkdayjobs.com/Capital_One",
    host: "capitalone.wd12.myworkdayjobs.com",
    tenant: "capitalone",
    site: "Capital_One",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "State Street",
    slug: "state-street",
    ats: "workday",
    careerUrl: "https://statestreet.wd1.myworkdayjobs.com/Global",
    host: "statestreet.wd1.myworkdayjobs.com",
    tenant: "statestreet",
    site: "Global",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "U.S. Bank",
    slug: "us-bank",
    ats: "workday",
    careerUrl: "https://usbank.wd1.myworkdayjobs.com/US_Bank_Careers",
    host: "usbank.wd1.myworkdayjobs.com",
    tenant: "usbank",
    site: "US_Bank_Careers",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "TD Bank",
    slug: "td-bank",
    ats: "workday",
    careerUrl: "https://td.wd3.myworkdayjobs.com/en-US/TD_Bank_Careers",
    host: "td.wd3.myworkdayjobs.com",
    tenant: "td",
    site: "TD_Bank_Careers",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "BMO",
    slug: "bmo",
    ats: "workday",
    careerUrl: "https://bmo.wd3.myworkdayjobs.com/External",
    host: "bmo.wd3.myworkdayjobs.com",
    tenant: "bmo",
    site: "External",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "PayPal",
    slug: "paypal",
    ats: "workday",
    careerUrl: "https://paypal.wd1.myworkdayjobs.com/jobs",
    host: "paypal.wd1.myworkdayjobs.com",
    tenant: "paypal",
    site: "jobs",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  // Wave 2 — insurers / payers
  {
    name: "Travelers",
    slug: "travelers",
    ats: "workday",
    careerUrl: "https://travelers.wd5.myworkdayjobs.com/External",
    host: "travelers.wd5.myworkdayjobs.com",
    tenant: "travelers",
    site: "External",
    searchTexts: [...DR_QUERIES],
    niche: "insurance",
  },
  {
    name: "AIG",
    slug: "aig",
    ats: "workday",
    careerUrl: "https://aig.wd1.myworkdayjobs.com/en-US/AIG",
    host: "aig.wd1.myworkdayjobs.com",
    tenant: "aig",
    site: "AIG",
    searchTexts: [...DR_QUERIES],
    niche: "insurance",
  },
];
