import type { Company } from "../../types.ts";

const DR_QUERIES = [
  "business continuity",
  "disaster recovery",
  "operational resilience",
  "continuity of business",
  "BCM",
  "crisis management",
] as const;

export const companies: Company[] = [
  {
    name: "Bank of America",
    slug: "bank-of-america",
    ats: "workday",
    careerUrl: "https://bankofamerica.wd1.myworkdayjobs.com/en-US/External",
    host: "bankofamerica.wd1.myworkdayjobs.com",
    tenant: "bankofamerica",
    site: "External",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "Wells Fargo",
    slug: "wells-fargo",
    ats: "workday",
    careerUrl: "https://wellsfargo.wd1.myworkdayjobs.com/en-US/wellsfargojobs",
    host: "wellsfargo.wd1.myworkdayjobs.com",
    tenant: "wellsfargo",
    site: "wellsfargojobs",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "Citigroup",
    slug: "citigroup",
    ats: "workday",
    careerUrl: "https://citi.wd5.myworkdayjobs.com/2",
    host: "citi.wd5.myworkdayjobs.com",
    tenant: "citi",
    site: "2",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "American Express",
    slug: "american-express",
    ats: "workday",
    careerUrl: "https://aexp.wd5.myworkdayjobs.com/aexp",
    host: "aexp.wd5.myworkdayjobs.com",
    tenant: "aexp",
    site: "aexp",
    searchTexts: [...DR_QUERIES],
    niche: "finance",
  },
  {
    name: "UnitedHealth Group",
    slug: "unitedhealth-group",
    ats: "workday",
    careerUrl: "https://uhgc.wd1.myworkdayjobs.com/UHGCareers",
    host: "uhgc.wd1.myworkdayjobs.com",
    tenant: "uhgc",
    site: "UHGCareers",
    searchTexts: [...DR_QUERIES],
    niche: "healthcare",
  },
  {
    name: "Elevance Health",
    slug: "elevance-health",
    ats: "workday",
    careerUrl: "https://elevancehealth.wd1.myworkdayjobs.com/ANT",
    host: "elevancehealth.wd1.myworkdayjobs.com",
    tenant: "elevancehealth",
    site: "ANT",
    searchTexts: [...DR_QUERIES],
    niche: "insurance",
  },
  {
    name: "Cigna",
    slug: "cigna",
    ats: "workday",
    careerUrl: "https://cigna.wd5.myworkdayjobs.com/cigna",
    host: "cigna.wd5.myworkdayjobs.com",
    tenant: "cigna",
    site: "cigna",
    searchTexts: [...DR_QUERIES],
    niche: "insurance",
  },
  {
    name: "Humana",
    slug: "humana",
    ats: "workday",
    careerUrl: "https://humana.wd5.myworkdayjobs.com/Humana_External_Career_Site",
    host: "humana.wd5.myworkdayjobs.com",
    tenant: "humana",
    site: "Humana_External_Career_Site",
    searchTexts: [...DR_QUERIES],
    niche: "healthcare",
  },
  {
    name: "HCA Healthcare",
    slug: "hca-healthcare",
    ats: "workday",
    careerUrl: "https://hcahr.wd1.myworkdayjobs.com/HCAHealthcare",
    host: "hcahr.wd1.myworkdayjobs.com",
    tenant: "hcahr",
    site: "HCAHealthcare",
    searchTexts: [...DR_QUERIES],
    niche: "healthcare",
  },
  {
    name: "MetLife",
    slug: "metlife",
    ats: "workday",
    careerUrl: "https://metlife.wd5.myworkdayjobs.com/MetLifeCareers",
    host: "metlife.wd5.myworkdayjobs.com",
    tenant: "metlife",
    site: "MetLifeCareers",
    searchTexts: [...DR_QUERIES],
    niche: "insurance",
  },
  {
    name: "Prudential",
    slug: "prudential",
    ats: "workday",
    careerUrl: "https://prudential.wd5.myworkdayjobs.com/pru",
    host: "prudential.wd5.myworkdayjobs.com",
    tenant: "prudential",
    site: "pru",
    searchTexts: [...DR_QUERIES],
    niche: "insurance",
  },
];
