import type { Company } from "./types.ts";

const PACKAGING_QUERY = "packaging";

export const companies: Company[] = [
  {
    name: "Kimberly-Clark",
    slug: "kimberly-clark",
    ats: "workday",
    careerUrl: "https://kimberlyclark.wd1.myworkdayjobs.com/GLOBAL",
    host: "kimberlyclark.wd1.myworkdayjobs.com",
    tenant: "kimberlyclark",
    site: "GLOBAL",
    searchText: PACKAGING_QUERY,
    niche: "cpg",
  },
  {
    name: "General Mills",
    slug: "general-mills",
    ats: "workday",
    careerUrl: "https://genmills.wd1.myworkdayjobs.com/GMI_External_Careers",
    host: "genmills.wd1.myworkdayjobs.com",
    tenant: "genmills",
    site: "GMI_External_Careers",
    searchText: PACKAGING_QUERY,
    niche: "food-beverage",
  },
  {
    name: "Sonoco",
    slug: "sonoco",
    ats: "workday",
    careerUrl: "https://sonoco.wd1.myworkdayjobs.com/CorporateCareers",
    host: "sonoco.wd1.myworkdayjobs.com",
    tenant: "sonoco",
    site: "CorporateCareers",
    searchText: PACKAGING_QUERY,
    niche: "industrial",
  },
  {
    name: "3M",
    slug: "3m",
    ats: "workday",
    careerUrl: "https://3m.wd1.myworkdayjobs.com/Search",
    host: "3m.wd1.myworkdayjobs.com",
    tenant: "3m",
    site: "Search",
    searchText: PACKAGING_QUERY,
    niche: "industrial",
  },
  {
    name: "Kenvue",
    slug: "kenvue",
    ats: "workday",
    careerUrl: "https://kenvue.wd5.myworkdayjobs.com/kenvue",
    host: "kenvue.wd5.myworkdayjobs.com",
    tenant: "kenvue",
    site: "kenvue",
    searchText: PACKAGING_QUERY,
    niche: "cpg",
  },
  {
    name: "Silgan Containers",
    slug: "silgan-containers",
    ats: "workday",
    careerUrl: "https://silgancontainers.wd1.myworkdayjobs.com/silgan",
    host: "silgancontainers.wd1.myworkdayjobs.com",
    tenant: "silgancontainers",
    site: "silgan",
    searchText: PACKAGING_QUERY,
    niche: "industrial",
  },
  {
    name: "Silgan Dispensing",
    slug: "silgan-dispensing",
    ats: "workday",
    careerUrl: "https://silgandispensing.wd501.myworkdayjobs.com/silgan",
    host: "silgandispensing.wd501.myworkdayjobs.com",
    tenant: "silgandispensing",
    site: "silgan",
    searchText: PACKAGING_QUERY,
    niche: "industrial",
  },
  {
    name: "Aptar",
    slug: "aptar",
    ats: "successfactors",
    careerUrl: "https://jobs.aptar.com",
    searchText: PACKAGING_QUERY,
    niche: "industrial",
  },
  {
    name: "Autoliv",
    slug: "autoliv",
    ats: "teamtailor",
    careerUrl: "https://careerunitedstates.autoliv.com/jobs",
    searchText: PACKAGING_QUERY,
    niche: "automotive",
  },
  {
    name: "General Motors",
    slug: "general-motors",
    ats: "workday",
    careerUrl: "https://generalmotors.wd5.myworkdayjobs.com/Careers_GM",
    host: "generalmotors.wd5.myworkdayjobs.com",
    tenant: "generalmotors",
    site: "Careers_GM",
    searchText: PACKAGING_QUERY,
    country: "USA",
    niche: "automotive",
  },
  {
    name: "Magna",
    slug: "magna",
    ats: "workday",
    careerUrl: "https://magna.wd3.myworkdayjobs.com/Magna",
    host: "magna.wd3.myworkdayjobs.com",
    tenant: "magna",
    site: "Magna",
    searchText: PACKAGING_QUERY,
    country: "USA",
    niche: "automotive",
  },
  {
    name: "Menasha",
    slug: "menasha",
    ats: "workday",
    careerUrl: "https://menasha.wd12.myworkdayjobs.com/MenashaCorp",
    host: "menasha.wd12.myworkdayjobs.com",
    tenant: "menasha",
    site: "MenashaCorp",
    searchText: PACKAGING_QUERY,
    country: "USA",
    niche: "industrial",
  },
  {
    name: "International Paper",
    slug: "international-paper",
    ats: "oracle",
    careerUrl:
      "https://iazbqy.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1",
    site: "CX_1",
    searchText: PACKAGING_QUERY,
    niche: "industrial",
  },
  {
    name: "PepsiCo",
    slug: "pepsico",
    ats: "phenom",
    careerUrl: "https://www.pepsicojobs.com/main",
    searchText: PACKAGING_QUERY,
    niche: "food-beverage",
  },
  {
    name: "Procter & Gamble",
    slug: "pg",
    ats: "phenom",
    careerUrl: "https://www.pgcareers.com/us/en",
    searchText: PACKAGING_QUERY,
    niche: "cpg",
  },
  {
    name: "The Coca-Cola Company",
    slug: "coca-cola-company",
    ats: "cws",
    careerUrl: "https://careers.coca-colacompany.com",
    host: "jobsapi-internal.m-cloud.io",
    orgId: "2110",
    searchText: PACKAGING_QUERY,
    facets: [
      "ats_portalid:CocaCola-Workday-External",
      "is_internal:coca-cola-careers",
      "primary_country:US",
    ],
    niche: "food-beverage",
  },
  {
    name: "DuPont",
    slug: "dupont",
    ats: "phenom",
    careerUrl: "https://careers.dupont.com/us/en",
    searchText: PACKAGING_QUERY,
    niche: "industrial",
  },
  {
    name: "Ball Corporation",
    slug: "ball",
    ats: "phenom",
    careerUrl: "https://jobs.ball.com",
    searchText: PACKAGING_QUERY,
    niche: "cpg",
  },
  {
    name: "Sealed Air",
    slug: "sealed-air",
    ats: "phenom",
    careerUrl: "https://jobs.sealedair.com",
    searchText: PACKAGING_QUERY,
    niche: "industrial",
  },
  {
    name: "Amcor",
    slug: "amcor",
    ats: "phenom",
    careerUrl: "https://www.amcor.com/careers",
    searchText: PACKAGING_QUERY,
    niche: "industrial",
  },
  {
    name: "Nestlé",
    slug: "nestle",
    ats: "successfactors",
    careerUrl: "https://www.nestlejobs.com",
    searchText: PACKAGING_QUERY,
    niche: "food-beverage",
  },
  {
    name: "Berlin Packaging",
    slug: "berlin-packaging",
    ats: "greenhouse",
    careerUrl: "https://job-boards.greenhouse.io/berlinpackaging",
    boardToken: "berlinpackaging",
    niche: "industrial",
  },
  {
    name: "Ernest Packaging",
    slug: "ernest-packaging",
    ats: "greenhouse",
    careerUrl: "https://job-boards.greenhouse.io/ernestpackagingsolutions",
    boardToken: "ernestpackagingsolutions",
    niche: "industrial",
  },
  {
    name: "Amazon",
    slug: "amazon",
    ats: "amazon",
    careerUrl: "https://www.amazon.jobs",
    searchText: "packaging engineer",
    country: "USA",
    niche: "industrial",
  },
];
